version: "3.7"
services:
  app:
    build:
      args:
        user: videoblog
        uid: 1000
      context: ../videoBlog-laravel-backend
      dockerfile: Dockerfile
    container_name: videoblog-app
    restart: always
    working_dir: /var/www/
    env_file:
      - .env
    volumes:
      - ../videoBlog-laravel-backend:/var/www
    networks:
      - videoblog

  frontend:
    container_name: frontend
    build:
      context: ../videoBlog-nuxt-frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - videoblog

  db:
    image: mysql
    container_name: videoblog-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - .env
    networks:
      - videoblog
    volumes:
      - videodb:/var/lib/mysql

  nginx:
    image: nginx
    container_name: videoblog-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../videoBlog-laravel-backend:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - videoblog

networks:
  videoblog:
    driver: bridge

volumes:
  videodb:
